name = "yellowsheet"
main = "src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# 8AM EST = 13:00 UTC (note: runs at 9AM during EDT/summer)
[triggers]
crons = ["0 13 * * *"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "teamupnc"

[browser]
binding = "BROWSER"
